name: CI

on:
  pull_request:
    branches:
      - main
env:
  TEST_TAG: devbox:latest-test

jobs:
  build:
    if: startsWith(github.head_ref, 'release-please') != true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Rebuild
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
        
      - name: Run tests
        run: docker run --rm ${{ env.TEST_TAG }} zsh --version

 
